CREATE TABLE users (
   id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   nome VARCHAR(255) NOT NULL,
   email VARCHAR(255) NOT NULL,
   senha TEXT NOT NULL,
   tipo VARCHAR(50) NOT NULL,
   ativo bool
);
